package com.skku.se7.dto.enums;

public enum PlatformType {
    LOCAL_SERVER, PERSONAL_COMPUTER,
    CLOUD_COMPUTING_GOOGLE,
    CLOUD_COMPUTING_AWS,
    CLOUD_COMPUTING_AZURE,
    CLOUD_COMPUTING_OTHER
}
